/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { StaticFruitDeliciousAnimated } from "./StaticFruitDeliciousAnimated";
export type { StaticSeeds } from "./StaticSeeds";
