/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { StaticFruitDeliciousAnimated__factory } from "./StaticFruitDeliciousAnimated__factory";
export { StaticSeeds__factory } from "./StaticSeeds__factory";
