name: Contracts Tests

on:
  push:
    branches: [ main ]
    paths: [ 'contracts/**' ]
  pull_request:
    branches: [ main ]
    paths: [ 'contracts/**' ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: contracts

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'

    - name: Setup pnpm
      uses: pnpm/action-setup@v4
      with:
        version: latest

    - name: Get pnpm store directory
      id: pnpm-cache
      shell: bash
      run: |
        echo "store_path=$(pnpm store path)" >> $GITHUB_OUTPUT

    - name: Setup pnpm cache
      uses: actions/cache@v4
      with:
        path: ${{ steps.pnpm-cache.outputs.store_path }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-

    - name: Install dependencies
      run: pnpm install --frozen-lockfile

    - name: Compile contracts
      run: pnpm run compile

    - name: Run live read-only tests
      run: pnpm run test:live
      env:
        BASE_MAINNET_RPC: ${{ secrets.BASE_MAINNET_RPC }}
        STATICFRUIT_ADDR: ${{ secrets.STATICFRUIT_ADDR }}
        STATICSEEDS_ADDR: ${{ secrets.STATICSEEDS_ADDR }}
        STATICFRUIT_SAMPLE_TOKENID: ${{ secrets.STATICFRUIT_SAMPLE_TOKENID }}

    - name: Run fork tests
      run: pnpm run test:fork
      env:
        BASE_MAINNET_RPC: ${{ secrets.BASE_MAINNET_RPC }}
        STATICFRUIT_ADDR: ${{ secrets.STATICFRUIT_ADDR }}
        STATICSEEDS_ADDR: ${{ secrets.STATICSEEDS_ADDR }}
        FORK_MAINNET: 1

    - name: Run coverage
      run: pnpm run coverage

    - name: Upload coverage reports
      uses: codecov/codecov-action@v4
      with:
        file: ./contracts/coverage.json
        flags: contracts
        name: contracts-coverage